// GraphData の TypeScript 型定義

// 確信度
export type Confidence = "perfect" | "high" | "medium" | "low";

// 新: 証明の進捗度
export type ProofProgress = "complete" | "mostly" | "partially" | "stub";

// 定義の進捗度
export type DefProgress = "complete" | "partially";

export type SorryFilter = "hasSorry" | "noSorry";
export type LineSizeCategory = "small" | "medium" | "large";

// 詳細分類の型
export type SubKind =
  | "theorem_manual" // 手動定義定理
  | "theorem_auto" // 自動生成定理
  | "definition" // 通常定義
  | "inductive" // 帰納型
  | "structure" // 構造体
  | "abbrev"; // 略記

export interface NodeMeta {
  name: string | null;
  summary: string | null;
  confidence: Confidence | null; // 確信度
  proofProgress: ProofProgress | null; // 証明進捗
  defProgress: DefProgress | null; // 定義進捗
  paperRef: string | null;
  isMainTheorem: boolean;
  axioms: string[] | null;
  axiomsHidden: string[] | null;
}

export interface NodeData {
  id: string;
  shortName: string;
  kind: "theorem" | "definition" | "axiom" | string;
  subKind?: SubKind | string; // 詳細分類
  filePath: string;
  hasSorry: boolean;
  meta: NodeMeta;
  dependencies: string[];
  lineStart: number | null;
  lineEnd: number | null;
  nonCommentLines: number | null;
  isAutoGenerated?: boolean;
}

// エッジの依存種類（8分類: ソースkind × 依存部位 × ターゲットkind）
export type EdgeKind =
  | "theorem_type_to_definition"
  | "theorem_type_to_theorem"
  | "theorem_value_to_definition"
  | "theorem_value_to_theorem"
  | "definition_type_to_definition"
  | "definition_type_to_theorem"
  | "definition_value_to_definition"
  | "definition_value_to_theorem";

export const THEOREM_VALUE_EDGE_KINDS: EdgeKind[] = [
  "theorem_value_to_definition",
  "theorem_value_to_theorem",
];

// エッジの視覚カテゴリ（実線/破線の区別用）
export type EdgeVisualKind = "type" | "value";

export interface EdgeData {
  source: string;
  target: string;
  kind?: EdgeKind; // オプショナルで後方互換性維持
}

export interface GraphMetadata {
  generatedAt: string;
  leanVersion: string;
  projectName: string;
}

export interface GraphStatistics {
  totalNodes: number;
  totalEdges: number;
  theoremCount: number;
  definitionCount: number;
  axiomCount: number;
  sorryCount: number;
  withProgressCount: number;
}

export interface GraphData {
  metadata: GraphMetadata;
  statistics: GraphStatistics;
  nodes: NodeData[];
  edges: EdgeData[];
}

// 依存関係フィルターのモード
export type DependencyFilterMode = "dependencies" | "dependents";

// 依存関係フィルターの状態
export interface DependencyFilter {
  nodeIds: Set<string>; // 選択されたノードID群
  mode: DependencyFilterMode; // 依存先 or 被依存先
  isActive: boolean; // フィルター有効フラグ
}

// フィルター状態
export interface FilterState {
  kinds: Set<string>;
  subKinds: Set<SubKind>; // 詳細分類フィルター
  confidence: Set<Confidence>; // 確信度フィルター
  proofProgress: Set<ProofProgress>; // 証明進捗フィルター
  defProgress: Set<DefProgress>; // 定義進捗フィルター
  sorryFilter: Set<SorryFilter>; // 両方選択 = 全表示、片方のみ = フィルター
  searchQuery: string;
  directories: Set<string>;
  paperRefFilter: string | null;
  mainTheoremSink: string | null; // 選択した主要定理の ID（1つのみ）
  alwaysShowMainTheorems: boolean; // 主要定理を常に表示するか
  lineSize: Set<LineSizeCategory>; // 行数フィルター
  dependencyFilter: DependencyFilter; // 依存関係フィルター
  edgeKinds: Set<EdgeVisualKind>; // エッジ種類フィルター（視覚カテゴリ）
  typeReachableOnly: boolean; // 人間検証対象フィルター（定理の証明から出るエッジを剪定）
}

// React Flow 用の拡張ノードデータ
export interface CustomNodeData extends NodeData {
  dependents: string[]; // 被依存（このノードに依存しているノード）
  isSink?: boolean; // 主要定理 sink として選択されているか
  isHighlighted?: boolean; // ハイライト状態（選択ノード + 直接依存・被依存）
  isSelected?: boolean; // 詳細パネルで選択されているか
  isVerificationTarget?: boolean; // 人間検証対象（typeReachable）か
  [key: string]: unknown; // React Flow Node 型の要件
}
