// TypeScript type definitions for GraphData

// Confidence level
export type Confidence = "perfect" | "high" | "medium" | "low";

// Proof progress level
export type ProofProgress = "complete" | "mostly" | "partially" | "stub";

// Definition progress level
export type DefProgress = "complete" | "partially";

export type SorryFilter = "hasSorry" | "noSorry";
export type LineSizeCategory = "small" | "medium" | "large";

// Sub-classification type
export type SubKind =
  | "theorem_manual" // Manually defined theorem
  | "theorem_auto" // Auto-generated theorem
  | "definition" // Regular definition
  | "inductive" // Inductive type
  | "structure" // Structure
  | "abbrev"; // Abbreviation

export interface NodeMeta {
  name: string | null;
  summary: string | null;
  confidence: Confidence | null; // Confidence level
  proofProgress: ProofProgress | null; // Proof progress
  defProgress: DefProgress | null; // Definition progress
  paperRef: string | null;
  isMainTheorem: boolean;
  axioms: string[] | null;
  axiomsHidden: string[] | null;
}

export interface NodeData {
  id: string;
  shortName: string;
  kind: "theorem" | "definition" | "axiom" | string;
  subKind?: SubKind | string; // Sub-classification
  filePath: string;
  hasSorry: boolean;
  meta: NodeMeta;
  dependencies: string[];
  lineStart: number | null;
  lineEnd: number | null;
  nonCommentLines: number | null;
  isAutoGenerated?: boolean;
}

// Edge dependency kind (8 categories: source kind x dependency site x target kind)
export type EdgeKind =
  | "theorem_type_to_definition"
  | "theorem_type_to_theorem"
  | "theorem_value_to_definition"
  | "theorem_value_to_theorem"
  | "definition_type_to_definition"
  | "definition_type_to_theorem"
  | "definition_value_to_definition"
  | "definition_value_to_theorem";

export const THEOREM_VALUE_EDGE_KINDS: EdgeKind[] = [
  "theorem_value_to_definition",
  "theorem_value_to_theorem",
];

// Edge visual category (for distinguishing solid/dashed lines)
export type EdgeVisualKind = "type" | "value";

export interface EdgeData {
  source: string;
  target: string;
  kind?: EdgeKind; // Optional for backward compatibility
}

export interface GraphMetadata {
  generatedAt: string;
  leanVersion: string;
  projectName: string;
}

export interface GraphStatistics {
  totalNodes: number;
  totalEdges: number;
  theoremCount: number;
  definitionCount: number;
  axiomCount: number;
  sorryCount: number;
  withProgressCount: number;
}

export interface GraphData {
  metadata: GraphMetadata;
  statistics: GraphStatistics;
  nodes: NodeData[];
  edges: EdgeData[];
}

// Dependency filter mode
export type DependencyFilterMode = "dependencies" | "dependents";

// Dependency filter state
export interface DependencyFilter {
  nodeIds: Set<string>; // Set of selected node IDs
  mode: DependencyFilterMode; // Dependencies or dependents
  isActive: boolean; // Whether the filter is active
}

// Filter state
export interface FilterState {
  kinds: Set<string>;
  subKinds: Set<SubKind>; // Sub-classification filter
  confidence: Set<Confidence>; // Confidence level filter
  proofProgress: Set<ProofProgress>; // Proof progress filter
  defProgress: Set<DefProgress>; // Definition progress filter
  sorryFilter: Set<SorryFilter>; // Both selected = show all, one only = filter
  searchQuery: string;
  directories: Set<string>;
  paperRefFilter: string | null;
  mainTheoremSink: string | null; // ID of the selected main theorem (only one)
  alwaysShowMainTheorems: boolean; // Whether to always show main theorems
  lineSize: Set<LineSizeCategory>; // Line count filter
  dependencyFilter: DependencyFilter; // Dependency filter
  edgeKinds: Set<EdgeVisualKind>; // Edge kind filter (visual category)
  typeReachableOnly: boolean; // Human verification target filter (prunes edges from theorem proofs)
}

// Extended node data for React Flow
export interface CustomNodeData extends NodeData {
  dependents: string[]; // Dependents (nodes that depend on this node)
  isSink?: boolean; // Whether selected as a main theorem sink
  isHighlighted?: boolean; // Highlight state (selected node + direct dependencies/dependents)
  isSelected?: boolean; // Whether selected in the detail panel
  isVerificationTarget?: boolean; // Whether this is a human verification target (typeReachable)
  [key: string]: unknown; // Required by React Flow Node type
}
