"use client";

import { memo } from "react";
import { Handle, Position, type Node } from "@xyflow/react";
import type { CustomNodeData } from "@/lib/types";
import {
  AXIOM_NODE_COLORS,
  CONFIDENCE_NODE_COLORS,
  NONE_CONFIDENCE_INLINE_STYLES,
  SORRY_GLOW,
} from "@/lib/constants";
import { calculateNodeDiameter, getNodeDegree, getNodeTextSizes, NODE_SIZE_CONFIG } from "@/lib/lineSize";
import { useTheme } from "@/components/ThemeProvider";
import { useTranslation } from "@/lib/i18n/LanguageContext";

type CustomNodeType = Node<CustomNodeData>;

interface CustomNodeComponentProps {
  data: CustomNodeData;
  selected?: boolean;
  targetPosition?: Position;
  sourcePosition?: Position;
}

function CustomNodeComponent({
  data,
  targetPosition = Position.Top,
  sourcePosition = Position.Bottom,
}: CustomNodeComponentProps) {
  const { t } = useTranslation();
  const { resolvedTheme } = useTheme();
  const confidence = data.meta.confidence ?? "none";
  const isTarget = data.isVerificationTarget ?? true;
  const colors =
    data.kind === "axiom"
      ? AXIOM_NODE_COLORS
      : CONFIDENCE_NODE_COLORS[confidence];

  // none confidence はインラインスタイルで確実に適用
  const isNoneInline = confidence === "none" && data.kind !== "axiom";
  const noneStyles = isNoneInline
    ? NONE_CONFIDENCE_INLINE_STYLES[resolvedTheme === "dark" ? "dark" : "light"]
    : null;
  const hasMeta = data.meta.name !== null;
  const isMainTheorem = data.meta.isMainTheorem;
  const isSink = data.isSink;
  const isAuto = data.isAutoGenerated;

  // ハイライト状態（未設定の場合はハイライト扱い）
  const isHighlighted = data.isHighlighted ?? true;

  const isTheorem = data.kind === "theorem";
  const isDefinition = data.kind === "definition";
  const isAxiom = data.kind === "axiom";

  // 動的サイズ計算
  const diameter = isSink
    ? NODE_SIZE_CONFIG.sinkDiameter
    : calculateNodeDiameter(getNodeDegree(data));

  // 形状: 全ノード完全な円形
  const shapeClass = "rounded-full";

  // サイズ: インラインスタイルで動的に設定
  const circleBase =
    "aspect-square flex items-center justify-center overflow-hidden";

  // テキストサイズ: 直径に応じて段階的に設定
  const { nameTextSize, subTextSize, badgeTextSize, badgeGap } = getNodeTextSizes(diameter, !!isSink);

  // sorry グロー
  const sorryClass = data.hasSorry ? SORRY_GLOW : "";

  return (
    <div
      className={`
        atlas-node
        border-2 ${isNoneInline && !isTarget ? "" : colors.border}
        ${shapeClass} ${circleBase}
        ${isTarget ? "" : isNoneInline ? "" : colors.bg}
        ${sorryClass}
        ${data.isSelected ? "ring-4 ring-blue-500 ring-offset-2 dark:ring-offset-[#0c0c18] shadow-xl z-10" : ""}
        ${isSink && !data.isSelected ? "ring-2 ring-orange-700 dark:ring-orange-700 ring-offset-2 dark:ring-offset-[#0c0c18] shadow-lg" : ""}
        ${isMainTheorem && !data.isSelected && !isSink ? "ring-2 ring-orange-600 dark:ring-orange-600" : ""}
        ${!isHighlighted ? "opacity-25" : ""}
        transition-all duration-150 hover:shadow-md
      `}
      style={{
        width: diameter,
        height: diameter,
        ...(isTarget ? { backgroundColor: "#b45a3c" } : {}),
        ...(noneStyles && !isTarget
          ? {
              backgroundColor: noneStyles.bg,
              borderColor: noneStyles.border,
            }
          : {}),
      }}
    >
      <Handle
        type="target"
        position={targetPosition}
        className="!bg-gray-400"
      />

      {isAuto ? (
        // 自動生成項目: 短縮名のみ表示
        <div
          className={`${nameTextSize} truncate text-center ${isTarget ? "" : isNoneInline ? "" : colors.text}`}
          style={isTarget ? { color: "#ffffff" } : noneStyles ? { color: noneStyles.text } : undefined}
        >
          {data.shortName}
        </div>
      ) : (
        // 通常ノード: 短縮名 + 日本語名 + バッジ
        <div className="flex flex-col items-center">
          <div className="w-full text-center">
            {/* 短縮名 */}
            <div
              className={`font-medium ${nameTextSize} truncate ${isTarget ? "" : isNoneInline ? "" : colors.text}`}
              style={isTarget ? { color: "#ffffff" } : noneStyles ? { color: noneStyles.text } : undefined}
            >
              {data.shortName}
            </div>

            {/* 日本語名 */}
            {hasMeta && data.meta.name && (
              <div
                className={`${subTextSize} ${isTarget ? "text-orange-100 dark:text-orange-100" : "text-gray-600"} truncate mt-0.5`}
              >
                {data.meta.name}
              </div>
            )}

            {/* バッジ行 */}
            <div
              className={`flex items-center justify-center ${badgeGap} flex-wrap`}
            >
              {/* Kind バッジ */}
              <span
                className={`${badgeTextSize} rounded bg-gray-100 text-gray-600 border border-gray-300`}
              >
                {isTheorem
                  ? t.node.thm
                  : isDefinition
                    ? t.node.def
                    : isAxiom
                      ? t.node.ax
                      : "?"}
              </span>

              {/* Sink バッジ */}
              {isSink && (
                <span
                  className={`${badgeTextSize} rounded bg-gray-100 text-gray-600 border border-gray-300 font-bold`}
                >
                  {t.node.sink}
                </span>
              )}

              {/* 主要定理バッジ */}
              {isMainTheorem && !isSink && (
                <span
                  className={`${badgeTextSize} rounded bg-gray-100 text-gray-600 border border-gray-300 font-medium`}
                >
                  {t.node.main}
                </span>
              )}

              {/* Paper Reference バッジ */}
              {data.meta.paperRef && (
                <span
                  className={`${badgeTextSize} rounded bg-gray-100 text-gray-600 border border-gray-300`}
                >
                  {data.meta.paperRef}
                </span>
              )}

              {/* Sorry 警告 */}
              {data.hasSorry && (
                <span
                  className={`${badgeTextSize} rounded bg-gray-100 text-gray-600 border border-gray-300`}
                >
                  sorry
                </span>
              )}
            </div>
          </div>
        </div>
      )}

      <Handle
        type="source"
        position={sourcePosition}
        className="!bg-gray-400"
      />
    </div>
  );
}

export const CustomNode = memo(CustomNodeComponent);
export type { CustomNodeType };
