/-
Copyright (c) 2025 LeanAtlas Project
LeanAtlas.GraphData - Dependency graph and metadata integration module
-/

import Lean
import LeanAtlas.Deps.Core
import LeanAtlas.Metadata.Extensions
import LeanAtlas.Config.Types

namespace LeanAtlas.GraphData.Core

open Lean
open LeanAtlas.Metadata
open LeanAtlas.Config

/-- Node metadata (includes progress information and attribute data) -/
structure NodeMeta where
  name : Option String
  summary : Option String
  confidence : Option LeanAtlas.Metadata.Confidence
  proofProgress : Option LeanAtlas.Metadata.ProofProgress
  defProgress : Option LeanAtlas.Metadata.DefProgress
  paperRef : Option String
  isMainTheorem : Bool
  axioms : Option (Array Name)
  axiomsHidden : Option (Array Name)
  deriving Inhabited

/-- Node dependency with kind information -/
structure NodeDepWithKind where
  name : Name
  kind : String   -- "type" | "value"
  deriving Inhabited

/-- Graph node data -/
structure NodeData where
  id : Name
  shortName : String
  kind : String
  subKind : String
  filePath : String
  hasSorry : Bool
  progressMeta : NodeMeta
  dependencies : Array Name
  dependenciesWithKind : Array NodeDepWithKind
  lineStart : Option Nat
  lineEnd : Option Nat
  nonCommentLines : Option Nat
  isAutoGenerated : Bool
  deriving Inhabited

/-- Edge dependency kind (8 variants: source kind × dep site × target kind) -/
inductive EdgeKind
  | theoremTypeToDefinition
  | theoremTypeToTheorem
  | theoremValueToDefinition
  | theoremValueToTheorem
  | definitionTypeToDefinition
  | definitionTypeToTheorem
  | definitionValueToDefinition
  | definitionValueToTheorem
  deriving Repr, BEq, Inhabited

/-- Graph edge data -/
structure EdgeData where
  source : Name
  target : Name
  kind : EdgeKind
  deriving Inhabited

/-- Graph metadata -/
structure GraphMetadata where
  generatedAt : String
  leanVersion : String
  projectName : String
  deriving Inhabited

/-- Graph statistics -/
structure GraphStatistics where
  totalNodes : Nat
  totalEdges : Nat
  theoremCount : Nat
  definitionCount : Nat
  axiomCount : Nat
  sorryCount : Nat
  withProgressCount : Nat
  deriving Inhabited

/-- Complete graph data -/
structure GraphData where
  metadata : GraphMetadata
  statistics : GraphStatistics
  nodes : Array NodeData
  edges : Array EdgeData
  deriving Inhabited

/-- Convert Deps.Core.DepKind to string -/
def depKindToString (dk : LeanAtlas.Deps.Core.DepKind) : String :=
  match dk with
  | .typeOnly => "type"
  | .valueOnly => "value"

/-- Convert EdgeKind to string -/
def edgeKindToString (ek : EdgeKind) : String :=
  match ek with
  | .theoremTypeToDefinition => "theorem_type_to_definition"
  | .theoremTypeToTheorem => "theorem_type_to_theorem"
  | .theoremValueToDefinition => "theorem_value_to_definition"
  | .theoremValueToTheorem => "theorem_value_to_theorem"
  | .definitionTypeToDefinition => "definition_type_to_definition"
  | .definitionTypeToTheorem => "definition_type_to_theorem"
  | .definitionValueToDefinition => "definition_value_to_definition"
  | .definitionValueToTheorem => "definition_value_to_theorem"

/-- Compute EdgeKind from source kind, dep kind, and target kind -/
def computeEdgeKind (sourceKind : String) (depKind : LeanAtlas.Deps.Core.DepKind)
    (targetKind : String) : EdgeKind :=
  match sourceKind == "theorem", depKind, targetKind == "theorem" with
  | true,  .typeOnly,  false => .theoremTypeToDefinition
  | true,  .typeOnly,  true  => .theoremTypeToTheorem
  | true,  .valueOnly, false => .theoremValueToDefinition
  | true,  .valueOnly, true  => .theoremValueToTheorem
  | false, .typeOnly,  false => .definitionTypeToDefinition
  | false, .typeOnly,  true  => .definitionTypeToTheorem
  | false, .valueOnly, false => .definitionValueToDefinition
  | false, .valueOnly, true  => .definitionValueToTheorem

/-- Get short name from a Name -/
def getShortName (n : Name) : String :=
  match n.components.getLast? with
  | some comp => comp.toString
  | none => n.toString

/-- Axioms that should be hidden by default -/
def isExcludedAxiom (n : Name) : Bool :=
  let excluded : Array Name := #[
    LeanAtlas.Config.stringToName "propext",
    LeanAtlas.Config.stringToName "Quot.sound",
    LeanAtlas.Config.stringToName "Classical.choice"
  ]
  excluded.any (fun ex => ex == n || ex.isSuffixOf n)

/-- Collect axioms used by a constant (transitively) -/
def collectAxiomsPartition (env : Environment) (root : Name) : (Array Name × Array Name) := Id.run do
  let mut axioms : NameSet := {}
  let mut hidden : NameSet := {}
  let mut visited : NameSet := {}
  let mut toProcess : Array Name := #[root]
  while h : toProcess.size > 0 do
    let current := toProcess[0]
    toProcess := toProcess.eraseIdx 0
    if visited.contains current then
      continue
    visited := visited.insert current
    let some ci := env.find? current | continue
    match ci with
    | .axiomInfo _ =>
        if isExcludedAxiom current then
          hidden := hidden.insert current
        else
          axioms := axioms.insert current
    | _ => pure ()
    let deps := ci.getUsedConstantsAsSet
    for dep in deps do
      if !visited.contains dep then
        toProcess := toProcess.push dep
  let axiomsSorted := axioms.toList.toArray.qsort (·.toString < ·.toString)
  let hiddenSorted := hidden.toList.toArray.qsort (·.toString < ·.toString)
  return (axiomsSorted, hiddenSorted)

/-- Count non-comment lines in Lean source -/
def countNonCommentLines (content : String) (startLine endLine : Nat) : Nat := Id.run do
  let lines := content.splitOn "\n"
  let linesArray := lines.toArray

  let startIdx := startLine - 1
  let endIdx := endLine

  let mut count := 0
  let mut inBlockComment := false

  for i in [startIdx:endIdx] do
    if h : i < linesArray.size then
      let line := linesArray[i]
      let trimmed := line.trimAscii.toString

      if trimmed.isEmpty then
        continue

      if inBlockComment then
        if LeanAtlas.Deps.Core.containsSubstr trimmed "-/" then
          inBlockComment := false
        continue

      if trimmed.startsWith "--" then
        continue

      if trimmed.startsWith "/-" then
        if !LeanAtlas.Deps.Core.containsSubstr trimmed "-/" || trimmed.endsWith "/-" then
          inBlockComment := true
        continue

      count := count + 1

  return count

/-- File cache type -/
abbrev FileCache := Std.HashMap String String

/-- Detect auto-generated name patterns -/
def isAutoGeneratedName (n : Name) : Bool :=
  let str := n.toString
  let lastComponent := match n.components.getLast? with
    | some comp => comp.toString
    | none => ""
  str.endsWith ".mk.inj" ||
  str.endsWith ".mk.injEq" ||
  str.endsWith ".eq_1" ||
  lastComponent == "noConfusion" ||
  lastComponent == "noConfusionType" ||
  lastComponent == "casesOn" ||
  lastComponent == "recOn" ||
  lastComponent == "rec" ||
  lastComponent == "brecOn" ||
  lastComponent == "below" ||
  lastComponent == "ibelow" ||
  lastComponent == "ctorIdx" ||
  lastComponent == "sizeOf_spec" ||
  lastComponent.startsWith "sizeOf" ||
  lastComponent == "toCtorIdx"

/-- Get parent name for auto-generated items (for metadata inheritance) -/
def getAutoGeneratedParent? (n : Name) : Option Name :=
  let str := n.toString
  if str.endsWith ".mk.inj" || str.endsWith ".mk.injEq" then
    n.getPrefix.getPrefix
  else if str.endsWith ".eq_1" then
    n.getPrefix
  else
    n.getPrefix

/-- Check if a constant is a structure field projection -/
def isStructureFieldProjection (env : Environment) (n : Name) : Bool :=
  match env.getProjectionFnInfo? n with
  | some projInfo =>
    let structName := projInfo.ctorName.getPrefix
    Lean.isStructure env structName
  | none => false

/-- Get parent structure name for a field projection -/
def getStructureFieldParent? (env : Environment) (n : Name) : Option Name :=
  match env.getProjectionFnInfo? n with
  | some projInfo =>
    let structName := projInfo.ctorName.getPrefix
    if Lean.isStructure env structName then some structName else none
  | none => none

/-- Infer file path from module name -/
def moduleToFilePath (modName : Name) : String :=
  let parts := modName.components.map (·.toString)
  String.intercalate "/" parts ++ ".lean"

/-- Build NodeMeta from Metadata (branching on kind for proofProgress/defProgress) -/
def buildNodeMeta (env : Environment) (n : Name) (hasSorryVal : Bool) (kind : String) : NodeMeta :=
  let newMeta := LeanAtlas.Metadata.getConstantMeta env n
  let hasAnyMeta := newMeta.confidence.isSome || newMeta.name.isSome
  let proofProgress :=
    if kind == "theorem" then
      newMeta.proofProgress.orElse (fun _ =>
        if hasAnyMeta then
          if hasSorryVal then some LeanAtlas.Metadata.ProofProgress.stub
          else some LeanAtlas.Metadata.ProofProgress.complete
        else none)
    else none
  let defProgress :=
    if kind == "definition" then
      newMeta.defProgress.orElse (fun _ =>
        if hasAnyMeta then
          if hasSorryVal then some LeanAtlas.Metadata.DefProgress.partially
          else some LeanAtlas.Metadata.DefProgress.complete
        else none)
    else none
  {
    name := newMeta.name
    summary := newMeta.summary
    confidence := newMeta.confidence
    proofProgress := proofProgress
    defProgress := defProgress
    paperRef := newMeta.paperRef
    isMainTheorem := newMeta.isMainTheorem
    axioms := none
    axiomsHidden := none
  }

/-- Build core node data (shared logic for sync and IO versions) -/
private def buildNodeDataCore (scope : ProjectScope) (env : Environment) (n : Name) : NodeData := Id.run do
  let kind := LeanAtlas.Deps.Core.classifyConstant env n
  let filePath := match getModuleFor? env n with
    | some modName => moduleToFilePath modName
    | none => "unknown"
  let hasSorryVal := hasSorry env n
  let isStructField := isStructureFieldProjection env n
  let isAuto := isAutoGeneratedName n || isStructField
  let subKind := LeanAtlas.Deps.Core.classifyConstantDetailed env n isAuto
  let targetName :=
    if isAutoGeneratedName n then
      getAutoGeneratedParent? n |>.getD n
    else if let some parent := getStructureFieldParent? env n then
      parent
    else
      n
  let nodeMeta := buildNodeMeta env targetName hasSorryVal kind
  let nodeMeta :=
    if nodeMeta.isMainTheorem then
      let (axioms, hidden) := collectAxiomsPartition env n
      { nodeMeta with axioms := some axioms, axiomsHidden := some hidden }
    else
      nodeMeta
  let depsWithKind := LeanAtlas.Deps.Core.getDirectDepsWithKind scope env n
  let deps := depsWithKind.map (·.name)
  let dependenciesWithKind := depsWithKind.map fun d => {
    name := d.name
    kind := depKindToString d.kind
  }

  let (lineStart, lineEnd) := match Lean.declRangeExt.find? env n with
    | some ranges =>
      let range := ranges.range
      (some range.pos.line, some range.endPos.line)
    | none => (none, none)

  return {
    id := n
    shortName := getShortName n
    kind := kind
    subKind := subKind
    filePath := filePath
    hasSorry := hasSorryVal
    progressMeta := nodeMeta
    dependencies := deps
    dependenciesWithKind := dependenciesWithKind
    lineStart := lineStart
    lineEnd := lineEnd
    nonCommentLines := none
    isAutoGenerated := isAuto
  }

/-- Build a single node (sync version, without non-comment line count) -/
def buildNodeData (scope : ProjectScope) (env : Environment) (n : Name) : NodeData :=
  buildNodeDataCore scope env n

/-- Build a single node (IO version, with non-comment line count) -/
def buildNodeDataIO (scope : ProjectScope) (env : Environment) (n : Name) (cache : IO.Ref FileCache) : IO NodeData := do
  let node := buildNodeDataCore scope env n
  let nonCommentLines ← match (node.lineStart, node.lineEnd) with
    | (some start, some endL) =>
      if node.filePath != "unknown" then
        let cacheMap ← cache.get
        let content ← match cacheMap.get? node.filePath with
          | some c => pure c
          | none => do
            let c ← IO.FS.readFile node.filePath
            cache.modify (·.insert node.filePath c)
            pure c
        pure (some (countNonCommentLines content start endL))
      else
        pure none
    | _ => pure none
  return { node with nonCommentLines := nonCommentLines }

/-- Convert string to EdgeKind -/
def stringToEdgeKind (s : String) : EdgeKind :=
  match s with
  | "theorem_type_to_definition" => .theoremTypeToDefinition
  | "theorem_type_to_theorem" => .theoremTypeToTheorem
  | "theorem_value_to_definition" => .theoremValueToDefinition
  | "theorem_value_to_theorem" => .theoremValueToTheorem
  | "definition_type_to_definition" => .definitionTypeToDefinition
  | "definition_type_to_theorem" => .definitionTypeToTheorem
  | "definition_value_to_definition" => .definitionValueToDefinition
  | "definition_value_to_theorem" => .definitionValueToTheorem
  | _ => .definitionTypeToDefinition

/-- Build edge array -/
def buildEdges (nodes : Array NodeData) : Array EdgeData := Id.run do
  let mut kindMap : Lean.NameMap String := {}
  for node in nodes do
    kindMap := kindMap.insert node.id node.kind
  let mut edges : Array EdgeData := #[]
  for node in nodes do
    for dep in node.dependenciesWithKind do
      let targetKind := kindMap.find? dep.name |>.getD "definition"
      let depKind := match dep.kind with
        | "value" => LeanAtlas.Deps.Core.DepKind.valueOnly
        | _ => LeanAtlas.Deps.Core.DepKind.typeOnly
      edges := edges.push {
        source := node.id, target := dep.name,
        kind := computeEdgeKind node.kind depKind targetKind
      }
  return edges

/-- Compute statistics -/
def computeStatistics (nodes : Array NodeData) (edges : Array EdgeData) : GraphStatistics := Id.run do
  let mut theoremCount := 0
  let mut definitionCount := 0
  let mut axiomCount := 0
  let mut sorryCount := 0
  let mut withProgressCount := 0

  for node in nodes do
    match node.kind with
    | "theorem" => theoremCount := theoremCount + 1
    | "definition" => definitionCount := definitionCount + 1
    | "axiom" => axiomCount := axiomCount + 1
    | _ => pure ()

    if node.hasSorry then
      sorryCount := sorryCount + 1

    if node.progressMeta.name.isSome then
      withProgressCount := withProgressCount + 1

  return {
    totalNodes := nodes.size
    totalEdges := edges.size
    theoremCount := theoremCount
    definitionCount := definitionCount
    axiomCount := axiomCount
    sorryCount := sorryCount
    withProgressCount := withProgressCount
  }

/-- Build complete graph data (sync version, without non-comment line count) -/
def buildGraphData (scope : ProjectScope) (env : Environment)
    (projectName : String) (timestamp : String) : GraphData := Id.run do
  let allConstants := LeanAtlas.Deps.Core.getAllProjectConstants scope env

  let mut nodes : Array NodeData := #[]
  for c in allConstants do
    nodes := nodes.push (buildNodeData scope env c)

  nodes := nodes.qsort (·.id.toString < ·.id.toString)

  let edges := buildEdges nodes

  let stats := computeStatistics nodes edges

  let graphMeta : GraphMetadata := {
    generatedAt := timestamp
    leanVersion := Lean.versionString
    projectName := projectName
  }

  return {
    metadata := graphMeta
    statistics := stats
    nodes := nodes
    edges := edges
  }

/-- Build complete graph data (IO version, with non-comment line count) -/
def buildGraphDataIO (scope : ProjectScope) (env : Environment)
    (projectName : String) (timestamp : String) : IO GraphData := do
  let allConstants := LeanAtlas.Deps.Core.getAllProjectConstants scope env

  let cache ← IO.mkRef (Std.HashMap.emptyWithCapacity 32 : FileCache)

  let mut nodes : Array NodeData := #[]
  for c in allConstants do
    let node ← buildNodeDataIO scope env c cache
    nodes := nodes.push node

  nodes := nodes.qsort (·.id.toString < ·.id.toString)

  let edges := buildEdges nodes

  let stats := computeStatistics nodes edges

  let graphMeta : GraphMetadata := {
    generatedAt := timestamp
    leanVersion := Lean.versionString
    projectName := projectName
  }

  return {
    metadata := graphMeta
    statistics := stats
    nodes := nodes
    edges := edges
  }

end LeanAtlas.GraphData.Core
