/-
Copyright (c) 2025 LeanAtlas Project
LeanAtlas.GraphData - JSON serialization
-/

import Lean.Data.Json
import LeanAtlas.GraphData.Core
import LeanAtlas.Metadata.Core

namespace LeanAtlas.GraphData.Json

open Lean
open LeanAtlas.GraphData.Core
open LeanAtlas.Metadata

/-- Convert Confidence to JSON string -/
def confidenceToJson (c : LeanAtlas.Metadata.Confidence) : Lean.Json :=
  Lean.Json.str c.toJsonString

/-- Convert ProofProgress to JSON string -/
def proofProgressToJson (p : LeanAtlas.Metadata.ProofProgress) : Lean.Json :=
  Lean.Json.str p.toJsonString

/-- Convert DefProgress to JSON string -/
def defProgressToJson (p : LeanAtlas.Metadata.DefProgress) : Lean.Json :=
  Lean.Json.str p.toJsonString

/-- Convert NodeMeta to JSON -/
def nodeMetaToJson (nodeMeta : NodeMeta) : Lean.Json := Lean.Json.mkObj [
  ("name", nodeMeta.name.map Lean.Json.str |>.getD Lean.Json.null),
  ("summary", nodeMeta.summary.map Lean.Json.str |>.getD Lean.Json.null),
  ("confidence", nodeMeta.confidence.map confidenceToJson |>.getD Lean.Json.null),
  ("proofProgress", nodeMeta.proofProgress.map proofProgressToJson |>.getD Lean.Json.null),
  ("defProgress", nodeMeta.defProgress.map defProgressToJson |>.getD Lean.Json.null),
  ("paperRef", nodeMeta.paperRef.map Lean.Json.str |>.getD Lean.Json.null),
  ("isMainTheorem", Lean.Json.bool nodeMeta.isMainTheorem),
  ("axioms",
    match nodeMeta.axioms with
    | some axioms => Lean.Json.arr (axioms.map (fun n => Lean.Json.str n.toString))
    | none => Lean.Json.null),
  ("axiomsHidden",
    match nodeMeta.axiomsHidden with
    | some axioms => Lean.Json.arr (axioms.map (fun n => Lean.Json.str n.toString))
    | none => Lean.Json.null)
]

/-- Convert NodeData to JSON -/
def nodeDataToJson (node : NodeData) : Lean.Json := Lean.Json.mkObj [
  ("id", Lean.Json.str node.id.toString),
  ("shortName", Lean.Json.str node.shortName),
  ("kind", Lean.Json.str node.kind),
  ("subKind", Lean.Json.str node.subKind),
  ("filePath", Lean.Json.str node.filePath),
  ("hasSorry", Lean.Json.bool node.hasSorry),
  ("meta", nodeMetaToJson node.progressMeta),
  ("dependencies", Lean.Json.arr (node.dependencies.map (Lean.Json.str ·.toString))),
  ("lineStart", node.lineStart.map (Lean.Json.num ·) |>.getD Lean.Json.null),
  ("lineEnd", node.lineEnd.map (Lean.Json.num ·) |>.getD Lean.Json.null),
  ("nonCommentLines", node.nonCommentLines.map (Lean.Json.num ·) |>.getD Lean.Json.null),
  ("isAutoGenerated", Lean.Json.bool node.isAutoGenerated)
]

/-- Convert EdgeKind to JSON string -/
def edgeKindToJson (ek : EdgeKind) : Lean.Json :=
  Lean.Json.str (edgeKindToString ek)

/-- Convert EdgeData to JSON -/
def edgeDataToJson (edge : EdgeData) : Lean.Json := Lean.Json.mkObj [
  ("source", Lean.Json.str edge.source.toString),
  ("target", Lean.Json.str edge.target.toString),
  ("kind", edgeKindToJson edge.kind)
]

/-- Convert GraphMetadata to JSON -/
def graphMetadataToJson (graphMeta : GraphMetadata) : Lean.Json := Lean.Json.mkObj [
  ("generatedAt", Lean.Json.str graphMeta.generatedAt),
  ("leanVersion", Lean.Json.str graphMeta.leanVersion),
  ("projectName", Lean.Json.str graphMeta.projectName)
]

/-- Convert GraphStatistics to JSON -/
def graphStatisticsToJson (stats : GraphStatistics) : Lean.Json := Lean.Json.mkObj [
  ("totalNodes", Lean.Json.num stats.totalNodes),
  ("totalEdges", Lean.Json.num stats.totalEdges),
  ("theoremCount", Lean.Json.num stats.theoremCount),
  ("definitionCount", Lean.Json.num stats.definitionCount),
  ("axiomCount", Lean.Json.num stats.axiomCount),
  ("sorryCount", Lean.Json.num stats.sorryCount),
  ("withProgressCount", Lean.Json.num stats.withProgressCount)
]

/-- Convert GraphData to JSON -/
def graphDataToJson (graph : GraphData) : Lean.Json := Lean.Json.mkObj [
  ("metadata", graphMetadataToJson graph.metadata),
  ("statistics", graphStatisticsToJson graph.statistics),
  ("nodes", Lean.Json.arr (graph.nodes.map nodeDataToJson)),
  ("edges", Lean.Json.arr (graph.edges.map edgeDataToJson))
]

/-- Convert to JSON string (compact) -/
def toJsonString (graph : GraphData) : String :=
  (graphDataToJson graph).compress

/-- Convert to JSON string (pretty-printed) -/
def toJsonStringPretty (graph : GraphData) : String :=
  (graphDataToJson graph).pretty

/-- Statistics-only JSON -/
def statisticsOnlyToJson (graph : GraphData) : Lean.Json := Lean.Json.mkObj [
  ("metadata", graphMetadataToJson graph.metadata),
  ("statistics", graphStatisticsToJson graph.statistics)
]

/-- Statistics-only JSON string -/
def toStatsJsonString (graph : GraphData) (pretty : Bool := false) : String :=
  let json := statisticsOnlyToJson graph
  if pretty then json.pretty else json.compress

end LeanAtlas.GraphData.Json
